### ISSUE TITLE
Routing from Frontend#index to Frontend#product not working

### ISSUE THREAD

**Issue by vicper-4** [nikalas/D0018E-Databasteknik#2]
Frontend#product behöver product som param. 
som det är nu så går den till /product.2 istället för /product/?id=2

**Comment by vicper-4** [comment]
Tror det ska göras i routes.rb. Försökte med
`get '/product/:id', to: 'frontend_pages#product'`
men då jag försökte så började den länka till /products/2 istället.

**Comment by vicper-4** [comment]
Börjar tro att rails kanske utgår ifrån att det ska vara plural och lägger på s. Kanske måste byta namn på nått.

**Comment by nikalas** [comment]
rails använder sig av plural, ja. Dock undrar jag vilken branch du kör? Jag refactorade alla routes i wip/bootstrap_layout, och den kan kanske också ha ställt till det?
